pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/ZobaerSayed/Comp-367-jenkins'
            }
        }
        
        stage('Build') {
            steps {
                def password = input(
                        id: 'passwordInput',
                        message: 'Enter the sudo password:',
                        parameters: [
                            [$class: 'PasswordParameterValue', name: 'PASSWORD', defaultValue: '']
                        ]
                    )
                    
                    // Execute the package installation command with sudo and password
                sh "echo ${password} | sudo -S apt update"
                sh "echo ${password} | sudo -S apt install -y maven"
                sh 'mvn package'
            }
        }
        
        stage('Run') {
            steps {
                // Start the application on port 7777
                sh 'mvn jetty:run'
                // or
                // sh 'java -jar -Dserver.port=7777 target/your-app.war'
            }
        }
    }
}
